Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,22 +1,27 @@
-name: My Workflow
-on: [push]
+name: CI/CD Pipeline with Border0 GitHub Action
+on:
+  push:
+  workflow_dispatch:
+    inputs:
+      debug:
+        type: boolean
+        description: Manual trigger
+        required: false
+        default: false
+
 jobs:
-  example:
+  gh-action-job:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Setup Border0 action
+      - name: A step that will always fail
+        run: |
+            echo "this step will wait 10 seconds and always fails"
+            sleep 10
+            exit 1
+      - name: Start Border0 in case of failure.
+        if: failure()
         uses: borderzero/gh-action@v2
         with:
           token: ${{ secrets.BORDER0_ADMIN_TOKEN }}
-          background-mode: true
-
-      - name: Your steps here
-        run: echo border0
-
-      - name: Clean-up for Border0
-        if: always()
-        uses: borderzero/gh-action@v2
-        with:
-          token: ${{ secrets.BORDER0_ADMIN_TOKEN }}
-          clean-up-mode: true
+          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
+          wait-for: 20
